# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse200Items(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, title: str=None, author: str=None, pub_date: str=None):  # noqa: E501
        """InlineResponse200Items - a model defined in Swagger

        :param title: The title of this InlineResponse200Items.  # noqa: E501
        :type title: str
        :param author: The author of this InlineResponse200Items.  # noqa: E501
        :type author: str
        :param pub_date: The pub_date of this InlineResponse200Items.  # noqa: E501
        :type pub_date: str
        """
        self.swagger_types = {
            'title': str,
            'author': str,
            'pub_date': str
        }

        self.attribute_map = {
            'title': 'title',
            'author': 'author',
            'pub_date': 'pub-date'
        }
        self._title = title
        self._author = author
        self._pub_date = pub_date

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200Items':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_items of this InlineResponse200Items.  # noqa: E501
        :rtype: InlineResponse200Items
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title(self) -> str:
        """Gets the title of this InlineResponse200Items.


        :return: The title of this InlineResponse200Items.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this InlineResponse200Items.


        :param title: The title of this InlineResponse200Items.
        :type title: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def author(self) -> str:
        """Gets the author of this InlineResponse200Items.


        :return: The author of this InlineResponse200Items.
        :rtype: str
        """
        return self._author

    @author.setter
    def author(self, author: str):
        """Sets the author of this InlineResponse200Items.


        :param author: The author of this InlineResponse200Items.
        :type author: str
        """
        if author is None:
            raise ValueError("Invalid value for `author`, must not be `None`")  # noqa: E501

        self._author = author

    @property
    def pub_date(self) -> str:
        """Gets the pub_date of this InlineResponse200Items.


        :return: The pub_date of this InlineResponse200Items.
        :rtype: str
        """
        return self._pub_date

    @pub_date.setter
    def pub_date(self, pub_date: str):
        """Sets the pub_date of this InlineResponse200Items.


        :param pub_date: The pub_date of this InlineResponse200Items.
        :type pub_date: str
        """
        if pub_date is None:
            raise ValueError("Invalid value for `pub_date`, must not be `None`")  # noqa: E501

        self._pub_date = pub_date
